export const PROCESS_PAYMENT_REQUEST = "PROCESS_PAYMENT_REQUEST";
export const PROCESS_PAYMENT_SUCCESS = "PROCESS_PAYMENT_SUCCESS";
export const PROCESS_PAYMENT_FAIL = "PROCESS_PAYMENT_FAIL";

export const CONFIRM_PAYMENT_REQUEST = "CONFIRM_PAYMENT_REQUEST";
export const CONFIRM_PAYMENT_SUCCESS = "CONFIRM_PAYMENT_SUCCESS";
export const CONFIRM_PAYMENT_FAIL = "CONFIRM_PAYMENT_FAIL";

export const GET_PDF_ACCESS_REQUEST = "GET_PDF_ACCESS_REQUEST";
export const GET_PDF_ACCESS_SUCCESS = "GET_PDF_ACCESS_SUCCESS";
export const GET_PDF_ACCESS_FAIL = "GET_PDF_ACCESS_FAIL";

export const CLEAR_PAYMENT_ERRORS = "CLEAR_PAYMENT_ERRORS";
