 const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
 const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
 const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
 const CLEAR_ERRORS = "CLEAR_ERRORS"

 export {
     ALL_PRODUCT_REQUEST,
     ALL_PRODUCT_SUCCESS,
     ALL_PRODUCT_FAIL,
     CLEAR_ERRORS
 }
