 const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
 const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
 const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
 const CLEAR_ERRORS = "CLEAR_ERRORS"

 const PRODUCT_DETAILS_REQUEST = "ALL_PRODUCT_DETAILS_REQUEST"
 const PRODUCT_DETAILS_SUCCESS = "ALL_PRODUCT_DETAILS_SUCCESS"
 const PRODUCT_DETAILS_FAIL = "ALL_PRODUCT_DETAILS_FAIL"

 const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
 const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
 const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"
 const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET"

 const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
 const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
 const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';
 const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET';

 export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'

 export {
     ALL_PRODUCT_REQUEST,
     ALL_PRODUCT_SUCCESS,
     ALL_PRODUCT_FAIL,
     CLEAR_ERRORS,
     PRODUCT_DETAILS_REQUEST,
     PRODUCT_DETAILS_SUCCESS,
     PRODUCT_DETAILS_FAIL,
     CREATE_PRODUCT_REQUEST,
     CREATE_PRODUCT_SUCCESS,
     CREATE_PRODUCT_FAIL,
     CREATE_PRODUCT_RESET,
     CREATE_REVIEW_REQUEST,
     CREATE_REVIEW_SUCCESS,
     CREATE_REVIEW_RESET,
     CREATE_REVIEW_FAIL,
 }
